### PR TITLE
Fix usage of SearchCondition with other Conditions in Elasticsearch and Opensearch

### PR DESCRIPTION
**Pull request by dhirtzbruch**
Should IMHO fix issue #313

### CODE REVIEW

**Comment by alexander-schranz** [comment]
Looks like the same issue appears on `Opensearch` can you implement the same mechanism on that Adapter? The `Lint` should be fixable via `php-cs-fixer` you can run it via `composer fix` command.

**Comment by dhirtzbruch** [comment]
@alexander-schranz Any idea why the opensearch test keeps failing in Github action? It works on my machine... ;-)

**Comment by alexander-schranz** [comment]
> Any idea why the opensearch test keeps failing in Github action? It works on my machine... ;-)

It sadly a race condition [problem of Github CI](https://github.com/actions/checkout/issues/518) not cloning the correct commit, you can ignore it as long as locally the issues are fixed.

**Comment by dhirtzbruch** [comment]
Oh, thanks - then it's working from my point of view.

**Comment by alexander-schranz** [comment]
@dhirtzbruch Thank you for the test and fix, good work 👍

**Pull request merged**
