### PR TITLE
Allow Symfony 7

### PR DESCRIPTION
**Pull request by ker0x**

### CODE REVIEW

**Comment by ToshY** [comment]
@alexander-schranz any chance you have time to review this one? Would love to upgrade to Symfony 7 myself 🙂

**Comment by alexander-schranz** [comment]
@ker0x Thx for the pull request can you rebase it to the latest changes of 0.2?

@ToshY I will try to find some time this week to test this.

**Comment by ker0x** [comment]
Hello @alexander-schranz , it's done 👍

**Comment by alexander-schranz** [comment]
@ker0x Thank you!

**Pull request merged**
